Repository CS2103JAN2018-W14-B1/main, pull requests merged in 2018-03, with the labels that each got.

#6 Added deleteTag(tag) to delete Tag
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.enhancement

#5 Added colors to tag labels
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/XmlSerializableAddressBookTest/invalidTagAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement

#44 Update UserGuide.adoc
  docs/UserGuide.adoc
Labels: Documentation

#46 Updated UserGuide with schedule command
  docs/UserGuide.adoc
Labels: Documentation

#45 Import command
  .gitignore
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/storage/Storage.java
  src/test/data/XmlAddressBookStorageTest/importsamplefile.xml
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalImportedPersons.java
Labels: status.ongoing

#70 Add appointment command
  .gitignore
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/EditedModelClassDiagram.png
  docs/images/EventModelClassDiagram.png
  docs/images/ExportCommandDiagram.png
  docs/images/ImportCommandFlowChart.png
  docs/images/Ui.png
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/SetAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SetTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/SetTaskCommandParser.java
  src/main/java/seedu/address/model/event/Appointment.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/model/event/PersonToMeet.java
  src/main/java/seedu/address/model/event/Task.java
  src/main/java/seedu/address/model/event/Title.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/test/data/XmlAddressBookStorageTest/importsamplefile.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/SetAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SetTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SetAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetTaskCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/event/EventTimeTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/XmlAdaptedTaskTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/ExportCommandBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalImportedPersons.java
  src/test/java/seedu/address/testutil/modelstub/ModelStub.java
  src/test/java/seedu/address/testutil/modelstub/ModelStubAcceptingEventAdded.java
  src/test/java/seedu/address/testutil/modelstub/ModelStubThrowingDuplicateEventException.java
Labels: status.ongoing, type.task

#107 DeleteShortcut Command, Improvised Personal Alias Command, Complete Tests Added
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteShortcutCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/ShortcutCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/shortcuts/ShortcutDoubles.java
  src/main/java/seedu/address/model/shortcuts/UniqueShortcutDoublesList.java
  src/test/java/seedu/address/logic/commands/DeleteShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ShortcutCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShortcutCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UniqueShortcutDoublesListTest.java
  src/test/java/seedu/address/model/shortcut/ShortcutDoubleTest.java
  src/test/java/seedu/address/testutil/modelstub/ModelStub.java
Labels: Completed
