Repository CS2103JAN2018-W14-B1/main, pull requests merged in 2018-04, with the labels that each got.

#101 Add remove command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/AppointmentListChangedEvent.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: Completed

#124 Export to CSV file depending on the interest of the user
  collated/functional/Sisyphus25-reused.md
  collated/functional/Sisyphus25.md
  collated/functional/randypx.md
  collated/functional/shanmu9898.md
  collated/test/Sisyphus25-reused.md
  collated/test/Sisyphus25.md
  collated/test/shanmu9898.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteShortcutCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/SetAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/SetTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ShortcutCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/shortcuts/ShortcutDoubles.java
  src/main/java/seedu/address/model/shortcuts/UniqueShortcutDoublesList.java
  src/main/java/seedu/address/storage/XmlAdaptedShortcutDouble.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ShortcutCard.java
  src/main/java/seedu/address/ui/ShortcutListPanel.java
  src/main/resources/Util/style.xsl
  src/main/resources/view/ShortcutListCard.fxml
  src/main/resources/view/ShortcutListPanel.fxml
  src/test/java/seedu/address/logic/commands/DeleteShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ShortcutCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShortcutCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UniqueShortcutDoublesListTest.java
  src/test/java/seedu/address/model/shortcut/ShortcutDoubleTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/ExportCommandHelper.java
  src/test/java/seedu/address/testutil/ShortcutCommandBuilder.java
  src/test/java/seedu/address/testutil/TypicalImportedPersons.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalShortcuts.java
  src/test/java/seedu/address/testutil/modelstub/ModelStub.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/ShortcutCardTest.java
Labels: Completed

#144 Export bug fix and Added Test Cases
  libs/commons-csv-1.5-sources.jar
  libs/commons-csv-1.5.jar
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/resources/Util/style.xsl
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/testutil/ExportCommandHelper.java
Labels: Completed

#147 added checks to prevent duplicates
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.bug

#151 UserGuideUpdate
  docs/UserGuide.adoc
Labels: Completed

#153 Fixed bugs
  src/main/java/seedu/address/commons/events/model/ClassListChangedEvent.java
  src/main/java/seedu/address/commons/events/model/StudentListChangedEvent.java
  src/main/java/seedu/address/logic/commands/FormCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/education/Class.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.bug

#162 Fix undo bug
  src/main/java/seedu/address/logic/commands/SetAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/testutil/modelstub/ModelStub.java
Labels: type.bug

#174 Updated Userguide
  docs/UserGuide.adoc
  docs/team/MukeshGadupudi.adoc
Labels: Going on
